name: Notify ServiceNow

on:
  push:
    branches:
      - main

jobs:
  create-servicenow-incident:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create ServiceNow Incident
      env:
        SNOW_INSTANCE: https://dev209441.service-now.com
        SNOW_USERNAME: admin
        SNOW_PASSWORD: elV5M=^qq2QW
      run: |
        incident_data=$(jq -n \
          --arg testKey "Hello from GitHub" \
          '{testKey: $testKey}')

        curl -X POST \
          -H "Content-Type: application/json" \
          -u $SNOW_USERNAME:$SNOW_PASSWORD \
          --data "$incident_data" \
          https://dev209441.service-now.com/api/sn_dpr_content/get_github_data
